# Generated by Django 6.0.1 on 2026-01-28 21:11

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_ventagarage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'Certificado/Reconocimiento', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'verbose_name': 'Venta de Garage', 'verbose_name_plural': 'Artículos Venta de Garage'},
        ),
        migrations.AddField(
            model_name='educacion',
            name='foto_certificado',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto_cv_v2/educacion/'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto_cv_v2/experiencia/'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha',
            field=models.DateField(validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagen',
            field=models.ImageField(upload_to='proyecto_cv_v2/certificados/'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_inicio',
            field=models.DateField(validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener exactamente 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(validators=[cv.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto_cv_v2/perfil/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto_cv_v2/venta_garage/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
